baseurl = "https://werz.is-a.dev/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 8
googleAnalytics = 'G-R2DLLBQDPX'
enableRobotsTXT = true

[params]
  hugoEncryptorLanguage = "en-us"
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # OS theme is default when not provided, but you can force it to "light" or "dark"
  defaultTheme = "dark"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3

  # Show reading time in minutes for posts
  showReadingTime = true

  # Show table of contents at the top of your posts (defaults to false)
  # Alternatively, add this param to post front matter for specific posts
  # toc = true

  # Show full page content in RSS feed items
  #(default is Description or Summary metadata in the front matter)
  # rssFullText = true
  
  #favicon
  favicon_ico = "/static/img/favicon.ico/"
# Path to favicon file
[languages]
  [languages.en]
    title = "Werz"
    subtitle = "CyberSecurity"
    keywords = "ctf, hackthebox, writeup, htb writeup, walkthrough, retired htb, hack the box, cybersecurtiy, capture the flag"
    copyright = "© 2022 Powered by Hugo"
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    # leave empty to disable, enter display text to enable
    # lastModDisplay = ""

    [languages.en.params.logo]
      logoText = "werz@blog:~$"
      logoHomeLink = "https://werz.is-a.dev/"
    # or
    #
    # path = "/static/logo.png"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "./whoami"
        url = "/about"
      #[[languages.en.menu.main]]
        #identifier = "ctf"
        #name = "CTF"
        #url = "/ctf"
      [[languages.en.menu.main]]
        identifier = "Archive"
        name = "./archive"
        url = "/archive"
      [[languages.en.menu.main]]
        identifier = "articles"
        name = "./articles"
        url = "/posts"


[permalinks]
  'posts' = '/:day/:month/:year/:filename/'
  'pdfs' = '/:day/:month/:year/:filename/'

[[params.social]]
  name = "github"
  url = "https://github.com/0xwerz"

